apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      automountServiceAccountToken: true
      serviceAccountName: argocd-repo-server
      containers:
        - name: uumpa
          command: ["/var/run/argocd/argocd-cmp-server"]
          # tag is commit hash from this repository, it is updated automatically by the CI to the latest commit
          image: ghcr.io/orihoch/uumpa-argocd-plugin/plugin:7b7dff11107ab435d3fc445d123c9cf6c5f37cf1
          # depending on the plugins you use, you might need to add some env vars here
          # env:
          #   - name: ...
          #   - value: ...
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /.cache
              name: uumpa-cache
            - mountPath: /tmp
              name: uumpa-temp
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: uumpa-plugin-config
      volumes:
        - name: uumpa-cache
          emptyDir: {}
        - name: uumpa-temp
          emptyDir: {}
        - name: uumpa-plugin-config
          configMap:
            name: uumpa-plugin
