apiVersion: v1
kind: ConfigMap
metadata:
  name: uumpa-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: uumpa
    spec:
      generate:
        command: [uumpa-argocd-plugin]
        args: [generate]
