apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.2/manifests/install.yaml
  - uumpa-plugin-configmap.yaml
  - argocd-repo-server-rbac.yaml

patchesStrategicMerge:
  - patch-argocd-repo-server-deployment.yaml
  - patch-argocd-cmd-params-cm.yaml
