on:
  push:
    branches:
      - main
    paths-ignore:
      - manifests/
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip &&\
          pip install -r requirements.txt &&\
          pip install -r tests/requirements.txt
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u orihoch --password-stdin &&\
          docker pull ghcr.io/orihoch/uumpa-argocd-plugin/plugin:latest &&\
          docker build --cache-from ghcr.io/orihoch/uumpa-argocd-plugin/plugin:latest -t ghcr.io/orihoch/uumpa-argocd-plugin/plugin:${{ github.sha }} . &&\
          docker push ghcr.io/orihoch/uumpa-argocd-plugin/plugin:${{ github.sha }} &&\
          docker tag ghcr.io/orihoch/uumpa-argocd-plugin/plugin:${{ github.sha }} ghcr.io/orihoch/uumpa-argocd-plugin/plugin:latest &&\
          docker push ghcr.io/orihoch/uumpa-argocd-plugin/plugin:latest
      - name: tests
        run: |
          sudo curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64 &&\
          sudo chmod +x /usr/local/bin/kind &&\
          sudo curl -Lo /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.8.4/argocd-linux-amd64 &&\
          sudo chmod +x /usr/local/bin/argocd &&\
          sudo curl -Lo /usr/local/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&\
          sudo chmod +x /usr/local/bin/kubectl &&\
          cat tests/kind.yaml.envsubst | envsubst > tests/kind.yaml &&\
          kind create cluster --config tests/kind.yaml &&\
          sed -i '/---snip---/q' "kustomize/tests/argocd/base/patch-argocd-repo-server-deployment.yaml" &&\
          pytest
