on:
  push:
    branches:
      - main
    paths:
      - "**.md"
jobs:
  ci:
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: check_md
        shell: bash
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qv '.md$'; then
            echo "::set-output name=md_only::false"
          else
            echo "::set-output name=md_only::true"
          fi
      - uses: ./.github/actions/build_push_latest
        if: steps.check_md.outputs.md_only == 'true'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
