on:
  push:
    branches:
      - main
    paths:
      - "**.md"
jobs:
  ci:
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: .github/actions/build_push_latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
